# Create a file called .github/workflows/auto-publish.yml
name: CI
on:
  pull_request:
    branches: [static_routing_api]
  push:
    branches: [static_routing_api]
jobs:
  main:
    name: Build, Validate and Deploy Locally
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: docs/index.bs
          DESTINATION: docs/index.html
          VALIDATE_MARKUP: true
          BUILD_FAIL_ON: fatal
